apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway: 
    options:
      waf:
        auditLogging:
          action: ALWAYS
          location: DYNAMIC_METADATA
        ruleSets:
          - ruleStr: |
              # Set audit log format to JSON
              # This must be set for the audit logs to be generated into Dynamic Metadata
              SecAuditLogFormat JSON
      dlp:
        enabledFor: ALL
        dlpRules:
          - actions:
            - actionType: SSN
              shadow: true
            - actionType: ALL_CREDIT_CARDS
              shadow: true
            - actionType: KEYVALUE
              keyValueAction:
                keyToMask: api-key
                maskChar: "*"
                name: api-key   # only used for logging
                percent:
                  value: 25  # % of regex match to mask
  proxyNames:
  - gateway-proxy
  useProxyProto: false
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            waf: '%DYNAMIC_METADATA(io.solo.filters.http.modsecurity:audit_log)%'
            api-key: '%REQ(api-key)%'
          path: /dev/stdout
