apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway: 
    options:
      waf:
        auditLogging:
          action: ALWAYS
          location: DYNAMIC_METADATA
        ruleSets:
          - ruleStr: |
              # Set audit log format to JSON
              # This must be set for the audit logs to be generated into Dynamic Metadata
              # even if ModSecurity isn't enabled or no rules are defined.
              #
              # I tried Native instead of JSON and it printed but didn't mask.
              SecAuditLogFormat JSON
      dlp:
        enabledFor: ALL
        dlpRules:
          - actions:
            - actionType: CUSTOM # CUSTOM is the default, so it's not necessary to put the actionType here
              customAction:
                name: api-key
                maskChar: "X"
                percent:
                  value: 25
                regexActions:
                  - regex: api-key:? *([^\\n]*)(?:\\n)
                    subgroup: 1
            - actionType: KEYVALUE
              keyValueAction:
                keyToMask: api-key
                maskChar: "*"
                name: api-key   # only used for logging
                percent:
                  value: 25  # % of regex match to mask
  proxyNames:
  - gateway-proxy
  useProxyProto: false
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            waf: '%DYNAMIC_METADATA(io.solo.filters.http.modsecurity:audit_log)%'
            api-key: '%REQ(api-key)%'
          path: /dev/stdout
